version: "3.9"

services:
  servicesservice:
    image: ${DOCKER_REGISTRY-}servicesservice
    depends_on:
      - sql
    ports:
      - "5003:5003" 
      - "5000:5000" 
    build:
      context: .
      dockerfile: ServicesService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:5003
      - DbConnection=Server=InnoClinicServicesDb,1433;Database=InnoClinicServices;MultipleActiveResultSets=true;TrustServerCertificate=True;User Id=SA;Password=InnoClinic123$;
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: InnoClinicServicesDb
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=InnoClinic123$