version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: RabbitMq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    container_name: IdentityServer
    depends_on:
      - identityserverdb
    ports:
      - "5000:80" 
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DbConnection=Server=IdentityDb,1433;Database=InnoClinicIdentity;MultipleActiveResultSets=true;TrustServerCertificate=True;User Id=SA;Password=InnoClinic123$;

  appointmentsservice:
    image: ${DOCKER_REGISTRY-}appointmentsservice
    container_name: AppointmentsService
    depends_on:
      - appointmentsdb
    ports:
      - "5004:5004" 
    build:
      context: .
      dockerfile: AppointmentsService.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:5004
      - DbConnection:User ID=InnoClinic;Password=InnoClinic123$;Host=AppointmentsDb;Port=5432;Database=InnoClinicAppointments;Pooling=true;Connection Lifetime=0;
      - IdentityPath=http://identityserver:80
      - IdentityPathOuter=http://localhost:5000
      - RabbitMq:Host=rabbitmq
      - RabbitMq:Username=rmuser
      - RabbitMq:Password=rmpassword



  appointmentsdb:
    image: "postgres:latest"
    container_name: AppointmentsDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "InnoClinicAppointments"  
      POSTGRES_PASSWORD: "InnoClinic123$"
      POSTGRES_USER: "InnoClinic"
    volumes:
      - 'appointments-dbdata:/var/opt/mssql'
 
  identityserverdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: IdentityDb
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=InnoClinic123$
    volumes:
      - 'identityserver-dbdata:/var/opt/mssql'



volumes:
  rabbitmq-data:
    driver: local
  offices-dbdata:
    driver: local
  profiles-dbdata:
    driver: local 
  services-dbdata:
    driver: local  
  identityserver-dbdata:
    driver: local 
  appointments-dbdata:
    driver: local